---
title: "Hallo \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Schrijf een interactief Python-project dat emoji gebruikt
meta_title: Python programmeer projecten voor kinderen en tieners | Hallo wereld
meta_description: Leer Python met de Raspberry Pi Foundation. Maak een interactief Python-codeer project dat emoji's gebruikt.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: What you will make
  - 
    title: Zeg hallo
  - 
    title: Sommen en datums
    completion:
      - engaged
  - 
    title: Gooi een dobbelsteen
  - 
    title: Get input
    completion:
      - internal
  - 
    title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: What can you do now?

