---
title: Hallo 🌍🌎🌏
hero_image: images/banner.png
description: Schrijf een interactief Python-project dat emoji gebruikt
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Inleiding
  - title: Zeg hallo
  - title: Sommen en datums
    completion: engaged
  - title: Gooi een dobbelsteen
  - title: Zin starter
  - title: Reflectie
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion: internal
  - title: Verbeter je project
    completion: external
  - title: Wat kun je verder nog doen?
