---
title: "Hallo \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Schrijf een interactief Python-project dat emoji gebruikt
meta_title: Python coding projects for kids and teens | Hello world
meta_description: Learn Python with the Raspberry Pi Foundation. Make an interactive Python coding project that uses emojis.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Wat ga je maken
  - 
    title: Zeg hallo
  - 
    title: Sommen en datums
    completion:
      - engaged
  - 
    title: Gooi een dobbelsteen
  - 
    title: Zin starter
    completion:
      - internal
  - 
    title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Wat kun je verder nog doen?
