title: Hello 🌍🌎🌏 
hero_image: images/banner.png
description: Write an interactive Python project that uses emoji
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Introduction
  - title: Say hello
  - title: Sums and dates
    completion: engaged  
  - title: Roll a dice
  - title: Sentence starter
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion: internal        
  - title: Upgrade your project
    completion: external  
  - title: What next?
