title: Hello 🌍🌎🌏 
hero_image: images/banner.png
description: Write an interactive Python project that uses emoji
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Say hello
  - title: Sums and dates
  - title: Roll a dice
  - title: Sentence starter
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
