---
title: "Hello \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: इमोजी का उपयोग करते हुए एक इंटरैक्टिव Python प्रोजेक्ट लिखें
meta_title: Python बच्चों और किशोरों के लिए प्रोजेक्ट कोडिंग | लक्ष्य अभ्यास
meta_description: रास्पबेरी पाई फाउंडेशन के साथ पायथन सीखें। एक इंटरैक्टिव पायथन कोडिंग प्रोजेक्ट बनाएं जो इमोजी का उपयोग करता हो।
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: आप क्या बनाएँगे
  - 
    title: hello कहें
  - 
    title: रकम और दिनांक
    completion:
      - engaged
  - 
    title: एक डाईस रोल करें
  - 
    title: इनपुट
    completion:
      - internal
  - 
    title: प्रश्नोत्तरी
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: चुनौती
    challenge: true
