---
title: "こんにちは \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: 絵文字を使用するインタラクティブなPythonプロジェクトを作成する
meta_title: Python coding projects for kids and teens | Hello world
meta_description: Learn Python with the Raspberry Pi Foundation. Make an interactive Python coding project that uses emojis.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: What you will make
  - 
    title: こんにちはと言う
  - 
    title: 計算と日付
    completion:
      - engaged
  - 
    title: サイコロを振る
  - 
    title: Get input
    completion:
      - internal
  - 
    title: ふりかえり
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
