---
title: "Hello \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: 絵文字を使用するインタラクティブなPythonプロジェクトを作成する
version: 4
listed: true
copyedit: true
last_tested: '2021-10-06'
steps:
  - 
    title: はじめに
  - 
    title: こんにちはと言う
  - 
    title: 計算と日付
    completion:
      - engaged
  - 
    title: サイコロを振る
  - 
    title: 文のとっかかり
    completion:
      - internal
  - 
    title: ふりかえり
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: プロジェクトをアップグレードする
  - 
    title: 次は何をしますか？
