# Emoji-variabelen om in je project te gebruiken

wereld = '🌍🌎🌏'
python = '🐍⌨️'
sommen = '✖️➗➖➕'
kalendar = '📅'
klock = '🕒'
projecten = '🎨🎮🔬'
leuk = '🎉🕶️'
dobbelsteen = '🎲'
eenhoorn = '🦄'
ruimte = '🚀'
blij = '😃'
dwaas = '😜'
hart = '❤️'
games = '🎮'
boeken = '📚'
sport = '⚽🎾👟'
groen = '♻️'
natuur = '🌳'
vuur = '🔥'
fonkelingen = '✨'
pleiten = '🥺'
honderd = '💯'
ster = '⭐'
geel_hart = '💛'
regenboog = '🌈'