---
title: Helo 🌍🌎🌏
hero_image: images/banner.png
description: Ysgrifennu prosiect Python rhyngweithiol sy'n defnyddio emoji
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Cyflwyniad
  - 
    title: Dweud helo
  - 
    title: Symiau a dyddiadau
    completion: engaged
  - 
    title: Taflu dis
  - 
    title: Dechrau brawddeg
    completion: internal
  - 
    title: Myfyrio
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Uwchraddio dy brosiect
  - 
    title: Beth nesaf?
