---
title: "Hallo \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Schreibe ein interaktives Python-Projekt, das Emojis verwendet
meta_title: Python Programmierprojekte für Kinder und Jugendliche | Hallo Welt
meta_description: Lerne Python mit der Raspberry Pi Foundation. Erstelle ein interaktives Python-Programmierprojekt, das Emojis verwendet.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Das wirst du machen
  - title: Sag Hallo
  - title: Rechnen und Daten
    completion:
      - engaged
  - title: Wirf einen Würfel
  - title: Satzanfang
    completion:
      - internal
  - title: Kurzes Quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Verbessere Dein Projekt