---
title: "Olá \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Escreva um projeto Python interativo que usa emojis
meta_title: Python coding projects for kids and teens | Hello world
meta_description: Learn Python with the Raspberry Pi Foundation. Make an interactive Python coding project that uses emojis.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Você vai fazer
  - 
    title: Diga olá
  - 
    title: Somas e datas
    completion:
      - engaged
  - 
    title: Role um dado
  - 
    title: Iniciador de frase
    completion:
      - internal
  - 
    title: Questionário rápido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Melhore o seu projeto
  - 
    title: E agora?
