---
title: "Dobrý den \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Napište interaktivní projekt Python, který používá emotikony
meta_title: Projekty kódování v Pythonu pro děti a dospívající | Ahoj světe
meta_description: Nauč se Python s Raspberry Pi Foundation. Vytvoř interaktivní projekt kódování Pythonu, který používá emotikony.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Co budeš dělat
  - 
    title: Řekni ahoj
  - 
    title: Hodnoty a operátory
    completion:
      - engaged
  - 
    title: Hod kostkou
  - 
    title: Vstup od uživatele
    completion:
      - internal
  - 
    title: Rychlý kvíz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Výzva
    challenge: true
  - 
    title: Co můžeš dělat nyní?
