---
title: "WITAJ \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Napisz interaktywny projekt w Pythonie, który używa emoji
meta_title: Projekty programistyczne Python dla dzieci i młodzieży | Hello world
meta_description: Naucz się Pythona z Raspberry Pi Foundation. Stwórz interaktywny projekt kodowania w Pythonie, który używa emoji.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: What you will make
  - 
    title: Powiedz cześć
  - 
    title: Sumy i daty
    completion:
      - engaged
  - 
    title: Rzuć kostką
  - 
    title: Get input
    completion:
      - internal
  - 
    title: Szybki quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
