---
title: "Bonjour \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Écris un projet Python interactif qui utilise des emojis
meta_title: Projets de codage Python pour enfants et adolescents | Bonjour le monde
meta_description: Apprends Python avec la Raspberry Pi Foundation. Crée un projet de codage Python interactif qui utilise des emojis.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: What you will make
  - 
    title: Dire bonjour
  - 
    title: Sommes et dates
    completion:
      - engaged
  - 
    title: Lancer un dé
  - 
    title: Get input
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: Et ensuite ?
