---
title: "Bonjour \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Écrire un projet Python interactif qui utilise des emoji
meta_title: Python coding projects for kids and teens | Hello world
meta_description: Learn Python with the Raspberry Pi Foundation. Make an interactive Python coding project that uses emojis.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Dire bonjour
  - 
    title: Sommes et dates
    completion:
      - engaged
  - 
    title: Lancer un dé
  - 
    title: Début de phrase
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Et ensuite ?
