---
title: "Hello \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Scrivi un progetto Python interattivo che utilizzi le emoji
meta_title: Progetti di codifica Python per bambini e adolescenti | Hello world
meta_description: Impara Python con la Raspberry Pi Foundation. Realizza un progetto di codifica Python interattivo che utilizzi gli emoji.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Quello che farai
  - 
    title: Diciamo Hello
  - 
    title: Somme e date
    completion:
      - engaged
  - 
    title: Lancia un dado
  - 
    title: Sentence starter
    completion:
      - internal
  - 
    title: Quiz veloce
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Migliora il tuo progetto
  - 
    title: E adesso?
