---
title: "Ciao \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Scrivi un progetto Python interattivo che utilizzi le emoji
meta_title: Progetti di programmazione Python per bambini e ragazzi | Ciao mondo
meta_description: Impara Python con la Raspberry Pi Foundation. Realizza un progetto di codifica Python interattivo che utilizzi gli emoji.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: What you will make
  - 
    title: Dire Ciao
  - 
    title: Somme e date
    completion:
      - engaged
  - 
    title: Lancia un dado
  - 
    title: Get input
    completion:
      - internal
  - 
    title: Quiz veloce
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
